const data = {
    products: [
        {
            _id:'1',
            name: 'Nike Slim Shirt',
            category: 'shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name: 'Lacoste Slim Shirt',
            category: 'shirts',
            image: '/images/p1.jpg',
            price: 100,
            countInStock: 37,
            brand: 'Lacoste',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name: 'Puma Slim Shirt',
            category: 'shirts',
            image: '/images/p1.jpg',
            price: 130,
            countInStock: 45,
            brand: 'Puma',
            rating: 4.8,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id:'4',
            name: 'Coinstar Slim Shirt',
            category: 'shirts',
            image: '/images/p1.jpg',
            price: 110,
            brand: 'Coinstar',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name: 'Rebook Slim Shirt',
            category: 'shirts',
            image: '/images/p1.jpg',
            price: 115,
            countInStock: 9,
            brand: 'Rebook',
            rating: 1.8,
            numReviews: 5,
            description: 'high quality product',
        },
        {
            _id:'6',
            name: 'Adidas Slim Shirt',
            category: 'shirts',
            image: '/images/p1.jpg',
            price: 140,
            countInStock: 0,
            brand: 'Adidas',
            rating: 3.2,
            numReviews: 25,
            description: 'high quality product',
        },
    ],
};

export default data;